version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:18.20
      - image: docker:24.0
    working_directory: ~/app

jobs:
  local-execution:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Setup Environment Variables
          command: |
            echo "MONGO_URI=$MONGO_URI" > .env
            echo "MONGO_USERNAME=$MONGO_USERNAME" >> .env
            echo "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Run Tests
          command: |
            npm test

  build-and-push:
    resource_class: large
    executor: docker-executor
    environment:
      REGISTRY: ayazumman.xyz
      IMAGE_NAME: circleci/solar-system
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t ${REGISTRY}/${IMAGE_NAME}:${CIRCLE_SHA1} .

      - run:
          name: Login to Harbor Registry
          command: |
            echo $HARBOR_PASSWORD | docker login ayazumman.xyz -u $HARBOR_USERNAME --password-stdin

      - run:
          name: Push Docker Image to Harbor
          command: |
            docker push ${REGISTRY}/${IMAGE_NAME}:${CIRCLE_SHA1}
            echo "Docker Image Pushed to Harbor"

workflows:
  build-and-deploy:
    jobs:
      - local-execution
      - build-and-push:
          requires:
            - local-execution
